name: TryHackMe Update Badge

on:
  schedule:
    # Make it run every 24 hour
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  tryhackme-badge-update:
    name: Update this repos tryhackme badge with the latest tryhackme image badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DhanushNehru/tryhackme-badge-action-workflow@v1.0
        with:
          username: 'elias.eder'
          user_id: '2372040'
          image_path: './assets/tryhackme-badge.png'
          GITHUB_TOKEN: ${{secrets.THM_TOKEN}}
